### ISSUE TITLE
On navigation No node with given id found

### ISSUE THREAD

**Issue by sfcgeorge** [rubycdp/cuprite#105]
Cuprite / Ferrum still seem to not quite handle navigation properly. For example in this spec I'm clicking submit on a form which navigates to another page. Sometimes it works, sometimes I get this error:

```
Failures:

  1) Enthusiast organizer does not participate
     Failure/Error: expect(page).to have_text "Who's going?"
     
     Capybara::Cuprite::ObsoleteNode:
       The element you are trying to interact with is either not part of the DOM, or is not currently visible on the page (perhaps display: none is set). It is possible the element has been replaced by another element and you meant to interact with the new element. If so you need to do a new find in order to get a reference to the new element.
     # ./spec/features/enthusiasts/books_an_activity_spec.rb:195:in `block (3 levels) in <main>'
     # ./spec/features/enthusiasts/books_an_activity_spec.rb:186:in `block (2 levels) in <main>'
     # ./spec/spec_helper.rb:32:in `block (2 levels) in <main>'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # Ferrum::NodeNotFoundError:
     #   No node with given id found
```

As you can see the expectation is just on `page` so there's no node for me to `find` again as the message suggests. 

I guess Cuprite needs to wait for the next page to finish loading, or refresh the `page` node on navigation, or automatically recover from this error somehow.

**Comment by route** [comment]
@sfcgeorge It should, do you have log file?

**Comment by tilsammans** [comment]
I have the same. Cuprite is just too fast sometimes, does not wait for a response after a form submit. When I run the same test again, it often passes. There is no way to tell.

The pages in question might have Ajax on them, or not. It happens for me in both scenarios.

```
cuprite 0.7.1
```

**Comment by tilsammans** [comment]
Also, these other versions:

```
Chrome 77.0.3865.120 (Ubuntu, 64 bit)
capybara 3.29.0
ferrum 0.5
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
```

**Comment by route** [comment]
@tilsammans do you have test and debug file? I can take a look but I need some data to figure it out

**Comment by route** [comment]
I need logs

**Comment by brunaportugal** [comment]
I have encountered the same issue as @sfcgeorge, but didn't find any solution to it online. How did you guys solve this problem?

I'm currently using these versions:

```
cuprite (0.11)
capybara (>= 2.1, < 4)
ferrum (~> 0.9.0)
```

**Comment by sfcgeorge** [comment]
@brunaportugal hi, sorry for not sharing the solution we found already! I believe a colleague fixed this by simply increasing the timeouts:

```ruby
Capybara.register_driver :cuprite do |app|
  Capybara::Cuprite::Driver.new(
    app,
    timeout:         15,
    process_timeout: 30
    # ... any extra config
  )
end
Capybara.javascript_driver = :cuprite
```

Feels too simple but hopefully that was it 😄

**Comment by brunaportugal** [comment]
@sfcgeorge thanks for the quick reply! Unfortunately this solution isn't working for me 😞

We have a method that takes screenshots of the error, and according to that Capybara/Cuprite does reach the page that I want. I've tried different matchers (_have_text, have_context, have_css_) and also different parts of the text, but for some reason I keep getting the same error. Anyone has an idea of what might be happening?

**Comment by route** [comment]
@brunaportugal why don't you turn headful mode and see what's happening meanwhile adding `slowmo` option? Maybe page has reloaded at the time of querying node?
