### ISSUE TITLE
Date field input is not working

### ISSUE THREAD

**Issue by vanboom** [rubycdp/cuprite#115]
Rails 4 application....
This works with chromedriver but not with cuprite:  
```
fill_in "Date", with: "01/01/2018"
```
The date field value goes to nil, confirmed by watching in headded mode.   I have tried other date formats "01-01-2018", "01-January-2018" without success.

**Comment by route** [comment]
This is how it is in cuprite specs `fill_in "date_field", with: "2016-02-14"`

**Comment by vanboom** [comment]
That works perfectly - thanks.  I was attempting to follow the way that Chrome displays the field on screen.
