### ISSUE TITLE
System tests hang indefinitely on Ubuntu 20.04

### ISSUE THREAD

**Issue by djvergad** [rubycdp/cuprite#123]
On Ubuntu 20.04, chromium is not available as a `deb` package, but only through `snap`. 

This causes system tests to hang without any useful message, as the tests seem to be running but do nothing.

The solution is to install chromium as a `deb` package from unofficial repositories, as explained here: https://askubuntu.com/a/1206153, but it is not at all obvious what the problem is.

Thus, I propose until `snap` is supported, to add an error message if chromium is detected to be from a snap, and/or to add a warning on `README.md`

**Comment by route** [comment]
There was an explanation from the beginning https://github.com/rubycdp/ferrum#install to install it from official channels, since cuprite is evetually a wrapper around Ferrum it applies here too.
