### ISSUE TITLE
Cuprite not running headlessly

### ISSUE THREAD

**Issue by caseyprovost** [rubycdp/cuprite#138]
When spinning up Cuprite on a new project on a newly set up machine I am seeing Cuprite running head-fully instead of headlessly. Would love your thoughts on this. It is probably user error, but I swear I have done this exact setup a dozen times with perfect success.

My config:

```ruby
require "capybara/cuprite"
Capybara.javascript_driver = :cuprite
Capybara.register_driver(:cuprite) do |app|
  browser_options = {}
  browser_options["no-sandbox"] = nil
  Capybara::Cuprite::Driver.new(
    app,
    browser_options: browser_options,
    window_size: [1400, 1400],
    js_errors: false,
    process_timeout: 10,
    headless: true
  )
end
```

Mac OS: 10.15.6
ChromeDriver: 85.0.4183.87
Chrome: Version 85.0.4183.121
Ruby Version: 2.6.1
Cuprite:  0.11
Capybara: 3.33.0

**Comment by route** [comment]
I need your log file, turn debug mode on and attach file here :)

**Comment by caseyprovost** [comment]
@route this is probably a dumb question, but how do you enable that? Below is the current config I am running to debug...but it is not spitting anything abnormal out in terminal or in test.log

```ruby
require "capybara/cuprite"

ENV["CUPRITE_DEBUG"]="true"

Capybara.register_driver(:cuprite) do |app|
  browser_options = {}
  browser_options["no-sandbox"] = nil
  Capybara::Cuprite::Driver.new(
    app,
    browser_options: browser_options,
    window_size: [1400, 1400],
    js_errors: false,
    process_timeout: 10,
    headless: true,
    inspector: true,
    debug: true,
    logger: $stdout,
  )
end

Capybara.javascript_driver = :cuprite
```

**Comment by caseyprovost** [comment]
OMG it was complete user error. I missed that RSpec now requires `driven_by` to be set

**Comment by route** [comment]
That's good you figured that out.

**Comment by adenta** [comment]
@caseyprovost  @route 
> OMG it was complete user error. I missed that RSpec now requires driven_by to be set

what does this mean? Currently cuprite is behaving weird in headless mode. Tests pass in non-headless mode, but fail in headless.

here are my two drivers:
```
Capybara.register_driver(:headless_cuprite) do |app|
  Capybara::Cuprite::Driver.new(app,  inspector: true, window_size: [1200, 800])
end
Capybara.javascript_driver = :headless_cuprite

Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(app, window_size: [1200, 800], headless: false, inspector: true)
end
```

In headless mode, I can't find a specific element by classname `find('.settings_button').click`, but this works in regular mode.
