### ISSUE TITLE
Capybara randomly not able to find elements

### ISSUE THREAD

**Issue by mbajur** [rubycdp/cuprite#141]
First of all - i'm not sure if that's a proper repo to report that issue, if not please forgive my ignorance and close this issue.

I have a pretty decent specs suite for one of my apps and there is one place that gives me headaches as it randomly fails on CI - like 8/10 of times. There is nothing really special about this check. It's about clicking a link:

```
    sign_in_as(create(:user))

    visit '/'
    click_link 'Projects'
    expect(page).to have_link '+ Create new project'
    find_link('+ Create new project').click
```

The error rspec gives me is 
```
Ferrum::NodeNotFoundError:
  Could not find node with given id
```

I tried putting sleep before that line but it didn't helped neither. Also, i have capybara-screenshot installed and i can see that this link is there every single time this test fails so i have really no idea what's going on in here. My stack:

- ruby 2.7.0
- capybara 3.9.0
- ferrum 0.9
- cuprite 0.11

any tips or dirty hacks much appreciated!

**Comment by route** [comment]
If you turn on debug log and attach it here or send it to my email I can take a look, otherwise it's fortune telling.

**Comment by georf** [comment]
I think you got the same problem. It should be fixed with #125

**Comment by mbajur** [comment]
Sorry for not responding, i'm not really able to provide any debug logs right now / in the nearest future so i guess this issue can be closed till then.

**Comment by MatheusPoliCamilo** [comment]
I'm having the same problem here, failing randomly with the error:

```
 Ferrum::NodeNotFoundError:
       Could not find node with given id
```

- Ruby 3.0.3
- Capybara 3.36.0
- Ferrum 0.11
- Cuprite 0.13

**Comment by route** [comment]
@MatheusPoliCamilo you better send logs and the test, otherwise it's not useful at all. Usually this happens in a bad written test, but there might be a lot of reasons.
