### ISSUE TITLE
Flaky tests when using 'within' block

### ISSUE THREAD

**Issue by jeromepl** [rubycdp/cuprite#145]
We are seeing some of our simple tests fail upwards of 80% of the time. For example:
```ruby
it "displays respondent gravatar" do
  visit(route)

  within "[data-test-key=project-page-content]" do
    img = page.find("img.MuiAvatar-img") # <--- When it fails, the test fails here
    expect(img[:src]).to eq expected_avatar_url
  end
end
```
The error message when running the test (again, only about 80% of the time):
```sh
1) ... displays respondent gravatar
     Failure/Error: img = page.find("img.MuiAvatar-img")

     Ferrum::JavaScriptError:
       TypeError: Cannot read property 'parentNode' of null
           at Cuprite.path (<anonymous>:102:23)
           at HTMLDivElement.<anonymous> (<anonymous>:1:31)
```

For a reason we don't yet understand, if we remove the within block from this test to change it to the following, then the test always passes successfully.
```ruby
it "displays respondent gravatar" do
  visit(route)

  img = page.find("[data-test-key=project-page-content] img.MuiAvatar-img")
  expect(img[:src]).to eq expected_avatar_url
end
```
Increasing the `default_max_wait_time` doesn't help as this type of error is not caught by Cuprite and thus not re-tried.

Because of the error stack trace pointing to Cuprite's javascript file, we suspect this is a Cuprite issue but so far haven't been able to reproduce the issue in Cuprite's own test suite. If you have any pointers to what we could try to run to help you reproduce the issue, please let me know

Ruby 2.6.6
Rails 6.1.3
Rspec 3.10.0 (rspec-rails 4.0.2, rspec-retry 0.6.2)
Cuprite 0.11 (Ferrum 0.9)
Capybara 3.35.3

**Comment by route** [comment]
That's interesting, could you come up with reproducible test?

**Comment by jeromepl** [comment]
We tried reproducing this issue in Cuprite's test suite without success.
The test:
```ruby
it "can click in a within block", :focus => true do
  @session.visit "/cuprite/click_test"
  @session.within :css, "[data-test-attr=body-test]" do
    @session.click_on "Link"
    log = @session.find(:css, "#log2")
    expect(log.text).to eq("link")
  end
end
```
With changes to `views/click_test.erb`:
- Add body attribute `<body data-test-attr="body-test">`
- Add button in body `<button id="link" class="box">Link</button>`
- And the following change to the onClick function (within the onload function) to simulate a load time:
```javascript
el.onclick = function() {
  log.textContent = this.id
  setTimeout(() => {
    log.id = "log2";
  }, 1000); // Capybara's default_max_wait_time is set to 1s
}
```

Yet, this did not reproduce the issue we are seeing in our codebase. Do you have any pointers to what potential differences could cause this test to work here as opposed to it failing in our code?

**Comment by route** [comment]
Could you turn on debug mode and send me log file in both cases? My email is in my profile.

**Comment by jeromepl** [comment]
What log file are you referring to? I am unaware of Cuprite generating any log files

**Comment by route** [comment]
See https://github.com/rubycdp/cuprite/blob/master/spec/spec_helper.rb and `logger:` option. Also you can set `FERRUM_DEBUG=true bundle exec rspec` and see the log in the console.

**Comment by jeromepl** [comment]
I have just sent you an email containing the log files, sorry for the wait!
