### ISSUE TITLE
segmentation fault on apple m1 when runnings specs with ruby 2.7.1

### ISSUE THREAD

**Issue by ktimothy** [rubycdp/cuprite#155]
I had an issue with system specs in my project, which I was able to track down to cuprite gem. I simply tried to run the cuprite's tests and got same segmentation fault, as I did with my tests:

```
[BUG] Segmentation fault at 0x0000000007ae7c20
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [-darwin20]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0001 p:---- s:0003 e:000002 (none) [FINISH]


-- Other runtime information -----------------------------------------------

* Loaded script: /Users/timofei.kovalev/.rbenv/versions/2.7.1/bin/rspec

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
```

[segfault.txt](https://github.com/rubycdp/cuprite/files/6460260/segfault.txt)
[ruby_2021-05-11-182044_RLX-TLL-MC001.crash.txt](https://github.com/rubycdp/cuprite/files/6460280/ruby_2021-05-11-182044_RLX-TLL-MC001.crash.txt)

**Comment by ktimothy** [comment]
I have traced the issue to the `Capybara::Result` class, and now it seems like the issue is connected with the Ruby lazy enumerators.

**Comment by route** [comment]
I don't think I can do something with it, first of all I don't have m1 to reproduce, second seems like it's ruby bug.
