### ISSUE TITLE
Switch browser to offline mode

### ISSUE THREAD

**Issue by adrienpoly** [rubycdp/cuprite#158]
I would like to test a progressive app and especially the behavior when the App goes offline.

I have seen some examples with Capybara for setting Chrome in offline mode by doing something like :

```ruby
params = {
  cmd:    'Network.emulateNetworkConditions',
  params: {
    offline:            true,
    latency:            0,
    downloadThroughput: 0,
    uploadThroughput:   0
  }
}

page.driver.browser.send(:bridge).send_command(params)
``` 

source : https://stackoverflow.com/questions/24027626/simulate-network-failure-offline-mode-in-capybara

I tried this with Cuprite

```ruby
params = {
          cmd: 'Network.emulateNetworkConditions',
          params: {
            offline: true,
            latency: 0,
            downloadThroughput: 0,
            uploadThroughput: 0
          }
        }

page.driver.browser.command(params)
```

but it hangs forever

any tips to achieve this? Thanks

**Comment by adrienpoly** [comment]
Ok it looks like that I am getting close to something with the following syntax

```ruby 
params = {
            offline: true,
            latency: 0,
            downloadThroughput: 0,
            uploadThroughput: 0
        }

page.driver.browser.page.command('Network.emulateNetworkConditions', params)
```

**Comment by route** [comment]
Both browser and page have `command` method it depends on the domain of CDP, I think it should be `page.driver.browser.command('Network.emulateNetworkConditions', params)` could you try and let us know?

**Comment by adrienpoly** [comment]
@route thanks it works. I now need to find how to enable service worker on chrome headless.

**Comment by twe4ked** [comment]
Hey,

I'm getting this error when trying to use this command:

```
Ferrum::BrowserError: 'Network.emulateNetworkConditions' wasn't found
```

Seems like this is a generic error coming back from Chrome. Any ideas?

Cheers!

**Comment by route** [comment]
@twe4ked  update Chrome

**Comment by route** [comment]
I've added methods for Network.emulateNetworkConditions and offline mode https://github.com/rubycdp/ferrum/pull/264

**Comment by twe4ked** [comment]
Thanks very much for the reply and implementing https://github.com/rubycdp/ferrum/pull/264.

I'm still getting an error after updating to the latest version of Chrome:

```
> page.driver.browser.process.browser_version
=> "HeadlessChrome/101.0.4951.54"
> page.driver.browser.command("Network.emulateNetworkConditions", offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0)
Ferrum::BrowserError: 'Network.emulateNetworkConditions' wasn't found
```

Any other ideas? I'm on an M1 Mac, doubt that's relevant but I thought I'd mention.

**Comment by route** [comment]
Turned out it should be called on page instance:
```
page.driver.browser.page.command("Network.emulateNetworkConditions", offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0)
```
