### ISSUE TITLE
Wrong order when using `fill_in` with Stripe Elements

### ISSUE THREAD

**Issue by marckohlbrugge** [rubycdp/cuprite#160]
I'm using [Stripe Elements](https://stripe.com/payments/elements) to accept credit card payments on my website. I've written some specs for this which work fine with the `webdrivers` gem. However, with `cuprite` some of the numbers that I enter with Capybara's `fill_in` get inserted out of order.

For example I use `fill_in "1234567890123456"` which results in this:

![CleanShot 2021-08-14 at 18 22 00@2x](https://user-images.githubusercontent.com/93276/129452803-fbe7afd0-6548-4957-b794-4b40eddca147.png)

I believe Stripe does some funky stuff with the text field to automatically format credit card numbers in pairs of 4 digits. I'm sure it's well tested and should work fine in most modern browsers as it does with `chromedriver`. But it seems like Cuprite has some trouble with it.

For reference, you can see Stripe Elements in action here: https://stripe.dev/elements-examples/

**Comment by route** [comment]
Thank you, I'll take a look at this page and will try to reproduce

**Comment by marckohlbrugge** [comment]
Sorry for more following up earlier. I thought I left another reply but apparently didn't.

Anyway. I think I solved this by removing a workaround that was needed for Capybara. With Cuprite it's no longer necessary and actually works flawlessly.

So no need to reproduce. The issue can be closed.

**Comment by route** [comment]
Gotcha, thank you @marckohlbrugge
