### ISSUE TITLE
debug(binding) is showing a chrome deprecation error page on chrome

### ISSUE THREAD

**Issue by JCTD** [rubycdp/cuprite#163]
I noticed that Chrome is unhappy with something in the debug(binding) feature because when it's called, it opens an error message on Chrome. Please see attached screenshot below.

<img width="1158" alt="Screen Shot 2021-09-10 at 5 57 11 PM" src="https://user-images.githubusercontent.com/7025236/132922346-8fdc4608-4e79-4d86-9186-eb6a1a7b6e01.png">

**Comment by route** [comment]
This is a duplicate of https://github.com/rubycdp/cuprite/issues/161
