### ISSUE TITLE
Rename url_blacklist / url_whitelist

### ISSUE THREAD

**Issue by odlp** [rubycdp/cuprite#165]
Hello,

Thanks for Cuprite & Ferrum - they're great.

Would the project be open to a contribution towards more inclusive language, specifically renaming:

- `url_blacklist` -> `url_blocklist`
- `url_whitelist` -> `url_allowlist`

Perhaps the old terms could be left as aliases and marked as deprecated until the next major version.

I'd be happy to raise a PR for this.

Cheers,
Oli

**Comment by route** [comment]
Hi @odlp I think I'm ok with that if there are aliases

**Comment by IamNaN** [comment]
Migrating the default branch to "main" would be another idea.
