### ISSUE TITLE
Unable to run rspec w/ Cuprite in Rails 7

### ISSUE THREAD

**Issue by simmerz** [rubycdp/cuprite#180]
Rails 6.1.4.4 works. Rails 7.0 fails with:

```
Cliver::Dependency::NotFound:
            Could not find an executable for the browser. Try to make it available on the PATH or set environment variable for example BROWSER_PATH="/usr/bin/chrome"
```

Setup is docker with a remote browserless.io image.

On investigating this a little further, when instantiating `Cuprite::Browser::Driver.new(app, options)` it appears none of the options get passed in, and instead there is a `window_size: [1400,1400]` option passed in. The only place I can see that is in one of the tests in the Cuprite codebase, so I'm unsure how that's getting passed through!

**Comment by lonnv** [comment]
Wanted to comment because we have the same issue, in Rails 7.0

**Comment by lonnv** [comment]
@simmerz I was able to work around it for now by registering the driver under a different name:

```
Capybara.register_driver(:foobar) do |app|
  Capybara::Cuprite::Driver.new(app,options)
end

Capybara.javascript_driver = :foobar

```

**Comment by route** [comment]
Investigating...

**Comment by baswenneker** [comment]
Not sure if it matters but I have the same issue. The workaround mentioned by @lonnv works but now my tests hit a timeout. I'm using rails 7 inside a docker container (evil martians setup https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing) and working on an Apple Macbook pro M1.

**Comment by swanson** [comment]
This PR for Rails 7 seems to be causing the issue: https://github.com/rails/rails/pull/42790 

If you name your configured driver `:cuprite` it will conflict with this method in Rails and your settings will be ignored: https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/system_testing/driver.rb#L78-L80

**Comment by swanson** [comment]
Appears to be fixed here: https://github.com/rails/rails/pull/42511

**Comment by route** [comment]
Right, so I'm afraid it's different type of issue @baswenneker you are facing
I'm going to close this one as it appears a bug on rails side

**Comment by elalemanyo** [comment]
@baswenneker Did you find a solution? I am having the same issue 😬

**Comment by mtomov** [comment]
I came across the issue of not being able to register a new driver called `cuprite`. 

Indeed

```ruby
Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(
    app,
    window_size: [1200, 800],
    browser_options: {},
    ...
  )
end
```

is a no go because Rails registers `:cuprite` as a driver name, so there's no way to re-register it. As mentioned above, you could simply call your driver `my_cuprite` and all will work. Alternatively, you can supply `options` to `driven_by` that would end up in the registered driver.

See
https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/system_test_case.rb#L156-L160

For example:


```ruby
Capybara.default_driver = Capybara.javascript_driver = :cuprite


RSpec.configure do |config|
  # ...

  config.prepend_before(:each, type: :system) do

    # Use JS driver always
    driven_by Capybara.javascript_driver, options: {
      window_size: [1200, 800],
      browser_options: {},
      # Increase Chrome startup wait time (required for stable CI builds)
      process_timeout: 10,
      # Enable debugging capabilities
      inspector: true,
      # Allow running Chrome in a headful mode
      headless: !ENV["BROWSER"],
      url_blacklist: [],
    }
  end
end

```
