### ISSUE TITLE
How to go offline?

### ISSUE THREAD

**Issue by aliciapaz** [rubycdp/cuprite#189]
I've been trying to find a way to test a PWA end-to-end using Cuprite as my driver, but I haven't find any way of either temporarily disabling the app server or switching the headless browser into offline mode.

I've seen some resources regarding this issue (stackoverflow, blog posts, etc.) but they all refer to Capybara + Selenium.

I'd appreciate your help on this!

**Comment by route** [comment]
There's no such ability now, but it can be easy to implement judging by this.

https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions
https://github.com/gr2m/headless-chrome-test/issues/1#issuecomment-313826914

I'll try to take a stab soon

**Comment by route** [comment]
Was implemented in Ferrum and will land on Cuprite in the new release.
