### ISSUE TITLE
How to load chrome extensions?

### ISSUE THREAD

**Issue by fanantoxa** [rubycdp/cuprite#191]
Hey! I've found problem that I can't resolve by myself. Could you take a look please?

There are extensions in google chrome. Sometime in tests it's very useful to have some like react/redux devtools (or other) to debug bug in application.
Currently when I run test with cuprite (not heedlessly) extensions setting is disabled (so I can't install any).
Also with `Selenium::WebDriver::Chrome` I'm able to load `.crx` (file that can be downloaded from [store](https://chrome.google.com/webstore/category/extensions?hl=en))
Like:
```
Selenium::WebDriver::Chrome::Options.new.tap do |options|
  options.add_extension(<extension_path>)
end
```
and pass it to the `Capybara::Selenium::Driver` as options.

Is there any way how I can load Chrome with `.crx` extensions using cuprite driver?

**Comment by route** [comment]
Hi! I think the easiest thing to do is to use this [flag](https://peter.sh/experiments/chromium-command-line-switches/#load-extension) while running Chrome and you can pass them to the browser using https://github.com/rubycdp/ferrum#customization and `:browser_options` hash.

**Comment by tetienne** [comment]
@fanantoxa Did you succeed to load extension finally?
