### ISSUE TITLE
`cannot load such file -- capybara/cuprite (LoadError)`

### ISSUE THREAD

**Issue by phylor** [rubycdp/cuprite#210]
With version 0.14 it seems we can't require the Capybara driver anymore.

Reproducable with the following:

```ruby
#!/usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "cuprite"
end

require "capybara/cuprite"
```

Error:

```
cannot load such file -- capybara/cuprite (LoadError)
```

@route Can you reproduce this issue? Is there something else we need to do, which wasn't necessary in version 0.13?

**Comment by vakuum** [comment]
I have the same problem.

The cuprite-0.14.gem file seems to be "empty": https://github.com/rubycdp/cuprite/issues/211
