### ISSUE TITLE
Cuprite.scrollIntoViewport does not properly handle elements hidden by overlays

### ISSUE THREAD

**Issue by ryanong** [rubycdp/cuprite#220]
https://github.com/rubycdp/cuprite/compare/main...ryanong:cuprite:click-overlay?expand=1
Is an example test that fails

This happens because `scrollIntoViewIfNeeded` does not handle when an element is hidden by an overlay. Selenium by default checks to see if element has an overlay and attempts to scroll through the elements.

https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/javascript/atoms/action.js#L707

Some solution could be to scroll every time. Or scroll if element is overlayed.

**Comment by route** [comment]
I'll check thanks for reporting.
