### ISSUE TITLE
Release/Publish new version of cuprite that depends on ferrum 0.15.0

### ISSUE THREAD

**Issue by 100terres** [rubycdp/cuprite#266]
### Details

The latest version of Cuprite depends on [ferrum ~> 0.14.0](https://github.com/rubycdp/cuprite/blob/v0.15/cuprite.gemspec#L28), but the 0.15.0 version of Ferrum includes some bug fixes that our team would greatly benefit from. Since the main branch already depends on the latest version of Ferrum, we were wondering if it would be possible to publish a new version of Cuprite to include these updates. Please let us know if there's anything we can do to help facilitate this process 😊

Thank you

**Comment by route** [comment]
@100terres do you guys have a big suit of tests? have you tried running them on master?
