### ISSUE TITLE
drag support?

### ISSUE THREAD

**Issue by dreyks** [rubycdp/cuprite#67]
I can see the skipped specs so it's definitely on the radar. Any specific plans/drafts? I might take a stab at this if time allows

**Comment by route** [comment]
No timeline yet, PRs are always welcome :)

**Comment by trusche** [comment]
This might be a bit hackish but does the trick for me (using rspec for a Rails app):

```ruby
module CupriteHelpers
  def click_and_drag(from, to)
    x1, y1 = find(from).native.node.find_position
    x2, y2 = find(to).native.node.find_position

    mouse = page.driver.browser.mouse
    mouse.move(x: x1, y: y1)
    mouse.down
    mouse.move(x: x2, y: y2)
    mouse.up
  end
end

RSpec.configure do |config|
  config.include CupriteHelpers, type: :system
end
```

**Comment by matpowel** [comment]
👍 definitely a needed feature, the click_and_drag workaround didn't work for me, I need to look into why
